apiVersion: v1
kind: ConfigMap
metadata:
  name: wrk-scripts
data:
  post.lua: |
    wrk.method = "POST"
    wrk.headers["Content-Type"] = "application/json"
    -- Small payload; server builds DataFrame of rows
    local body = '{"instances":[[5.1,3.5,1.4,0.2],[6.2,2.8,4.8,1.8],[5.9,3.0,5.1,1.8]]}'
    wrk.body = body
